wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.7
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736286241
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 19
      - 37
      - 45
      - 61
      4: 3.12.7
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 64
concept:
  desc: null
  value: notes
data_standardization:
  desc: null
  value: false
dropout_p:
  desc: null
  value: 0.25
hidden_layer_sizes:
  desc: null
  value:
  - 512
l2_weight_decay:
  desc: null
  value: 0.001
learning_rate:
  desc: null
  value: 0.001
model_layer:
  desc: null
  value: 0
model_size:
  desc: null
  value: L
model_type:
  desc: null
  value: MUSICGEN_TEXT_ENCODER
num_outputs:
  desc: null
  value: 12
output_type:
  desc: null
  value: multiclass
label_column_name:
  desc: null
  value: root_note_pitch_class
