wandb_version: 1

batch_size:
  value: 64
concept:
  value: chord_progressions
data_standardization:
  value: false
dropout_p:
  value: 0.25
hidden_layer_sizes:
  value: []
l2_weight_decay:
  value: null
learning_rate:
  value: 1.0e-05
model_layer:
  value: 0
model_size:
  value: L
model_type:
  value: MUSICGEN_AUDIO_ENCODER
