wandb_version: 1

batch_size:
  value: 64
concept:
  value: notes
data_standardization:
  value: false
dropout_p:
  value: 0.5
hidden_layer_sizes:
  value: []
l2_weight_decay:
  value: 0.0001
learning_rate:
  value: 1.0e-05
model_layer:
  value: 0
model_size:
  value: L
model_type:
  value: MUSICGEN_TEXT_ENCODER
